version: '3.8'
services:
  newrelic:
    image: newrelic/php-daemon
    networks:
      - internal
    restart: unless-stopped
    logging:            
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proxy:
    external: true